version: "3.8"

services:
  frontend:
    image: node:20-alpine
    container_name: vite_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development

  msg-service:
    image: openjdk:21-jdk
    container_name: msg-service
    ports:
      - "50011:50011"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 50010
    volumes:
      - ./msg-backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  user-service:
    image: openjdk:21-jdk
    container_name: user-service
    ports:
      - "50010:50010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./user-backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - db

volumes:
  db_data:
